site_name: Riot-cpp
nav: 
    - Home: index.md
    - Getting Started: 
      - Installation: 'Getting Started/installation.md'
      - Basic Usage: 'Getting Started/usage.md'
    - Implementation: 
      - Endpoints: 'Implementation/endpoints.md'
      - Handlers: 'Implementation/handlers.md'
      - Logging: 'Implementation/logging.md'
    - Contributing: 
      - How to Contribute: 'Contributing/contributing.md'
      - Authors: 'Contributing/contributing.md'

plugins: [] 
use_directory_urls: false

theme: 
    name: gitbook
