site_name: Riot-cpp
nav: 
    - Home: index.md
    - Getting Started: 
      - Installation: installation.md
      - Basic Usage: usage.md
    - Implementation: 
      - Endpoints: endpoints.md
      - Handlers: handlers.md
      - Logging: logging.md
    - Contributing: 
      - How to Contribute: contributing.md
      - Authors: contributing.md

plugins: [] 
use_directory_urls: false

theme: 
    name: gitbook
